name: Node.js Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and update npm
      run: |
        npm install
        if [[ "${{ matrix.node-version }}" == "18.x" || "${{ matrix.node-version }}" == "20.x" ]]; then
          npm install -g npm@latest
        else
          npm install -g npm@8
        fi
    - run: npm run build-browser
    - run: npm test
    - run: npm run test:integration
    - run: npm run test:playwright

  test-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: MINGW64
            install: mingw-w64-x86_64-nodejs
          - msystem: UCRT64
            install: mingw-w64-ucrt-x86_64-nodejs
          - msystem: CLANG64
            install: mingw-w64-clang-x86_64-nodejs

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: ${{ matrix.install }}
    - name: Set up Node.js environment
      shell: msys2 {0}
      run: |
        echo "Checking Node.js and npm versions:"
        node --version
        npm --version
        echo "Updating PATH:"
        echo "$MSYS2_PATH" >> $GITHUB_PATH
        echo "$(cygpath -w $(npm root -g))" >> $GITHUB_PATH
        echo "$(cygpath -w $(npm bin -g))" >> $GITHUB_PATH

    - name: Install dependencies
      shell: msys2 {0}
      run: |
        npm install

    - name: Run tests
      shell: msys2 {0}
      run: |
        npm run build-browser
        npm test
        npm run test:integration
        npm run test:playwright
